import { Button } from "@/components/ui/button";

const FieldOperations = () => {
  return (
    <div className="px-48 flex flex-col border-t border-slate-300">
      <div className="text-xl font-black uppercase text-center py-10">
        Field Operations
      </div>
      <div>
        Field operations in electrostatics involve understanding and
        manipulating electric fields generated by static charges. These
        operations are essential in analyzing how charges interact with each
        other and their surroundings. Here’s a breakdown of the key concepts and
        operations
      </div>
      <div className="text-lg font-black  py-8">Gradient of a Scalar Field</div>
      <div>
        • The gradient is an operation applied to a scalar field (a field that
        assigns a single value to every point in space, such as temperature or
        electric potential).
        <br /> • It produces a vector field that points in the direction of the
        greatest rate of increase of the scalar field, and its magnitude
        indicates the rate of change in that direction.
      </div>

      <div className="font-bold">
        Gradient of a scalar V can be written as: &nabla; V
      </div>

      <div>
        1. The Gradient elements in spherical coordinates can be found as:
      </div>
      <div>2. The Gradient normal surface area is</div>
      <div>3. The Gradient Volume is</div>

      <div className="text-lg font-black  py-8">
        Divergence of a Scalar Field
      </div>
      <div>
        • The divergence is an operation applied to a scalar field (a field that
        assigns a single value to every point in space, such as temperature or
        electric potential).
        <br /> • It produces a vector field that points in the direction of the
        greatest rate of increase of the scalar field, and its magnitude
        indicates the rate of change in that direction.
      </div>

      <div className="font-bold">
        Divergence of a scalar V can be written as: &nabla; V
      </div>

      <div>
        1. The Differential elements in spherical coordinates can be found as:
      </div>
      <div>2. The Differential normal surface area is</div>
      <div>3. The Differential Volume is</div>

      <div className="text-lg font-black  py-8">
        Laplacian of a Scalar Field
      </div>
      <div>
        • The divergence is an operation applied to a scalar field (a field that
        assigns a single value to every point in space, such as temperature or
        electric potential).
        <br /> • It produces a vector field that points in the direction of the
        greatest rate of increase of the scalar field, and its magnitude
        indicates the rate of change in that direction.
      </div>

      <div className="font-bold">
        Laplacian of a scalar V can be written as: &nabla; V
      </div>

      <div>
        1. The Differential elements in spherical coordinates can be found as:
      </div>
      <div>2. The Differential normal surface area is</div>
      <div>3. The Differential Volume is</div>

      <div className="text-lg font-black  py-8">Curl of a Scalar Field</div>
      <div>
        • The divergence is an operation applied to a scalar field (a field that
        assigns a single value to every point in space, such as temperature or
        electric potential).
        <br /> • It produces a vector field that points in the direction of the
        greatest rate of increase of the scalar field, and its magnitude
        indicates the rate of change in that direction.
      </div>

      <div className="font-bold">
        Curl of a scalar V can be written as: &nabla; V
      </div>

      <div>
        1. The Differential elements in spherical coordinates can be found as:
      </div>
      <div>2. The Differential normal surface area is</div>
      <div>3. The Differential Volume is</div>
      <div className="flex justify-end mb-48">
        <Button className="px-6">Next</Button>
      </div>
    </div>
  );
};

export default FieldOperations;
